# Generated by Django 5.1.5 on 2025-01-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Table_Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_Name', models.CharField(max_length=200)),
                ('Last_Update', models.CharField(max_length=200)),
                ('Duration', models.CharField(max_length=100)),
                ('New_Update', models.CharField(max_length=100)),
            ],
        ),
    ]
