# Generated by Django 5.1.5 on 2025-01-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_Name', models.CharField(max_length=40)),
                ('Last_Update', models.DateTimeField()),
                ('Duration', models.CharField(max_length=3)),
                ('New_Update', models.CharField(max_length=40)),
            ],
        ),
    ]
