# Generated by Django 5.1.5 on 2025-01-28 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnc', '0003_alter_example_master_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example_master',
            name='Last_Update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
